include onedark.conf

font_family                JetBrainsMono Nerd Font Mono
font_size                  9.5
font_features              none
disable_ligatures          always

adjust_line_height         1

bold_font                  auto
bold_italic_font           auto
italic_font                auto

bell_on_tab                no
command_on_bell            no
cursor_shape               block
enable_audio_bell          no
visual_bell_duration       0.0

editor                     nvim
macos_thicken_font         1

draw_minimal_borders       false
hide_window_decorations    yes

tab_bar_background         none
tab_bar_edge               top
tab_bar_style              separator

active_tab_title_template  none
tab_separator              ''
# tab_title_template         " [{index}: {title.split(" ")[0]}] "
# tab_title_template         "[ {index} ]"
tab_title_template         "[{index}: {title[title.rfind('/')+1:]}]"
max_title_length           20

window_border_width        0.0pt
window_margin_width        0 0
window_padding_width       0

# keybindings

map kitty_mod+t            new_tab_with_cwd

map kitty_mod+w            close_tab
map kitty_mod+[            previous_tab
map kitty_mod+]            next_tab

map kitty_mod+f6           load_config_file
map kitty_mod+f5           edit_config_file

enabled_layouts splits:split_axis=horizontal

map f5                     launch --location=hsplit
map f6                     launch --location=vsplit

map kitty_mod+h            neighboring_window left
map kitty_mod+l            neighboring_window right
map kitty_mod+k            neighboring_window up
map kitty_mod+j            neighboring_window down
