theme = "onedarker"

[editor]
line-number = "relative"
scrolloff = 16
bufferline = "multiple"
gutters = ['line-numbers', 'spacer']
rulers = [80]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

